new code45

diff --git a/.github/workflows/python-ci.yml b/.github/workflows/python-ci.yml
--- a/.github/workflows/python-ci.yml
+++ b/.github/workflows/python-ci.yml
@@ -41,8 +41,10 @@ jobs:
         run: |
           python -m venv venv
           source venv/bin/activate
-          pip install flake8 pylint coverage pytest
+          pip install flake8 pylint coverage
+          pip install --upgrade pip
           pip install -r requirements.txt
+          pip install pytest
           flake8 myapp > flake8-report.txt || true
           pylint myapp > pylint-report.txt || true
           coverage run -m pytest
@@ -76,6 +78,7 @@ jobs:
 
   gitleaks:
     runs-on: ubuntu-latest
+    needs: lint_and_coverage
     steps:
       - uses: actions/checkout@v3
 
@@ -93,10 +96,9 @@ jobs:
 
   integration_tests:
     runs-on: ubuntu-latest
-    needs: gitleaks
+    needs: [trufflehog_secrets, gitleaks]
     steps:
       - uses: actions/checkout@v3
-
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
@@ -111,10 +113,9 @@ jobs:
 
   e2e_tests:
     runs-on: ubuntu-latest
-    needs: integration_tests
+    needs: [trufflehog_secrets, gitleaks]
     steps:
       - uses: actions/checkout@v3
-
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
@@ -129,7 +130,7 @@ jobs:
 
   semgrep_sast:
     runs-on: ubuntu-latest
-    needs: e2e_tests
+    needs: [trufflehog_secrets, gitleaks]
     steps:
       - uses: actions/checkout@v3
 
@@ -152,7 +153,7 @@ jobs:
 
   containerize:
     runs-on: ubuntu-latest
-    needs: semgrep_sast
+    needs: [integration_tests, e2e_tests, semgrep_sast]
     steps:
       - uses: actions/checkout@v3
 
@@ -173,7 +174,7 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-      - name: Rebuild Docker Image
+      - name: Rebuild Docker Image Locally
         uses: docker/build-push-action@v5
         with:
           context: .
@@ -192,7 +193,7 @@ jobs:
 
       - name: Run Trivy Scan
         run: |
-          trivy image flask-starter-app:latest --severity HIGH,CRITICAL --no-progress -f json -o trivy-report.json || echo "Trivy scan failed"
+          sudo trivy image flask-starter-app:latest --severity HIGH,CRITICAL --no-progress -f json -o trivy-report.json || echo "Trivy scan failed"
 
       - uses: actions/upload-artifact@v4
         with:
